### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rishiosaur** [rishiosaur/hn#1]
Build out a Notion page for all the functions in the graphql api

**Comment by rishiosaur** [comment]
https://www.notion.so/rishikothari/HN-Documentation-71a91e5385b04238b1548c6df928e807

**Comment by sarthaktexas** [comment]
@rishiosaur Consider using [Gitbook](https://gitbook.com)? It has modules specifically made for API documentation. You can transfer what you already made on Notion as well *and* you can sync it with a Github repo so you can have the Markdown files as a backup.
